### ISSUE TITLE
Use state from previous operation in subsequent post(...)

### ISSUE THREAD

**Issue by taylordowns2000** [sid-indonesia/OpenFn-antenatal-care#1]
Re: https://github.com/sid-indonesia/OpenFn-antenatal-care/blob/909544ee87fd303029ed0af3343abceed7142fab/expressions/kobo-to-fhir-server.js#L96

@muhammad-levi , (cc: @amberrignell ) [`post(path, params, callback)`](https://github.com/OpenFn/language-http/blob/main/src/Adaptor.js#L161-L179) takes an object with functions inside of it _or_ a function for that `params` argument. If you want to access state from some earlier operation, make sure you're using a function somewhere in there that can be resolved by calling it with state:
```js
// operation 1 adds something to state...
fn(state => ({ ...state, new: 17 }));

// operation 2 modifies state in some way...
fn(state => ({ ...state, new: state.new + 4 }));

// operation 3 makes a post using state...
post(
  '/api/whatever', // the path
  state => ({
    body: state.new, // will be 21!
    headers: 'x-api-token': 'shhhh'
  })
);
```

Note that if you're trying to access part of `state.data`, the convention is to use that `dataValue('jsonpath')` helper function. So you might be doing something like:

```js
// operation 1 adds something to state...
fn(state => ({ ...state, data: { count: 17 } }));

// operation 2 makes a post using state...
post(
  '/api/whatever', // the path
  {
    body: dataValue('count') // will be 17!
    headers: 'x-api-token': 'shhhh'
  }
);
```

I think the first example is more straightforward, but either should work.

**Comment by muhammad-levi** [comment]
@taylordowns2000 Cool! Thanks much, Taylor. ✌️

Oh yeah about access token from OAuth 2.0, I think it might be best in OpenFn.org use the `client_credentials` grant in the Credentials, then also add mechanism if the POST failed because access token is expired, then automatically get new access token by using the same information for getting the access token with `client_credentials` grant, then retry the POST.

What do you think? Is that a good way to approach the issue?

might be useful references:
https://developers.google.com/identity/protocols/oauth2
https://stackoverflow.com/a/43349958
https://cloud.google.com/apigee/docs/api-platform/security/oauth/oauth-20-client-credentials-grant-type

**Comment by muhammad-levi** [comment]
https://github.com/sid-indonesia/OpenFn-antenatal-care/blob/main/expressions/kobo-to-fhir-server.js#L426

I don't know why, but it is `null`
